// Auto-generated by tools/gen_logo.py — do not edit
#pragma once
#include <stdint.h>

#define LOGO_EDGE_COUNT  4082

extern const uint8_t logo_edge_x[LOGO_EDGE_COUNT];
extern const uint8_t logo_edge_y[LOGO_EDGE_COUNT];
