// Auto-generated by tools/gen_logo.py — do not edit
#pragma once
#include <stdint.h>

#define LOGO_BAR_COUNT   10
#define LOGO_MASK_BYTES  7200
#define LOGO_EDGE_COUNT  4082

typedef struct { uint8_t cx; uint8_t width; uint8_t max_h; } logo_bar_t;

extern const logo_bar_t logo_bars[LOGO_BAR_COUNT];
extern const uint8_t    logo_mask_bits[LOGO_MASK_BYTES];
extern const uint8_t    logo_edge_x[LOGO_EDGE_COUNT];
extern const uint8_t    logo_edge_y[LOGO_EDGE_COUNT];

static inline int logo_pixel(int x, int y) {
    int bit = y * 240 + x;
    return (logo_mask_bits[bit >> 3] >> (7 - (bit & 7))) & 1;
}
